apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: kube-logging
  labels:
    app: kibana
spec:
  type: LoadBalancer
  selector:
    app: kibana
  ports:
    - port: 5601
      targetPort: 5601  # Optional: explicitly match pod port
      protocol: TCP     # Optional: default TCP
  selector:
    app: kibana

